<!--
  Portfolio → Transactions. Port of the bundle's Transactions.dc.html.

  Every row is generated by the ledger, so this screen is a view of the same
  lots the holdings drawer shows. The reconciliation panel is the proof that
  those generated rows still add up to the stored positions.
-->
<script lang="ts">
  import { MONTHS, fmt, type LedgerRow } from '@snowline/core';
  import TopNav from '$lib/components/TopNav.svelte';
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();

  const S = $derived(data.screen);
  const K = $derived(S.constants);

  type Tab = 'Trades' | 'Incomes' | 'All';
  type SortKey = 'date' | 'shares' | 'price' | 'summ' | 'profit';

  let tab = $state<Tab>('Trades');
  let query = $state('');
  let ops = $state<string[]>([]);
  let sortKey = $state<SortKey>('date');
  let sortDir = $state(-1);
  let limit = $state(40);
  let selected = $state<string[]>([]);
  let deleted = $state<string[]>([]);
  let cols = $state({ fee: true, profit: true, note: true });
  let menu = $state<string | null>(null);
  let filtersOpen = $state(false);
  let reconOpen = $state(false);

  const PAGE = 40;

  /** Row date as a sortable serial. MONTHS is a const tuple, so widen to index it. */
  const MONTH_NAMES: readonly string[] = MONTHS;
  const dateSerial = (d: string) => {
    const p = String(d).split(' ');
    return (+p[2] || 0) * 10000 + (MONTH_NAMES.indexOf(p[1]) + 1) * 100 + (+p[0] || 0);
  };

  const visible = $derived(S.rows.filter((r) => !deleted.includes(r.id)));

  const filtered = $derived.by(() => {
    let list = visible.filter((r) =>
      tab === 'All' ? true : tab === 'Trades' ? r.kind !== 'income' : r.kind === 'income'
    );
    if (ops.length) list = list.filter((r) => ops.includes(r.operation));
    const q = query.trim().toLowerCase();
    if (q) {
      list = list.filter((r) =>
        `${r.ticker} ${r.name} ${r.operation} ${r.date} ${r.note ?? ''}`.toLowerCase().includes(q)
      );
    }
    return list;
  });

  /** Per-row profit: an income row books its cash, a trade marks to market. */
  function profitOf(r: LedgerRow) {
    const p = S.prices[r.ticker];
    if (r.kind === 'income') {
      return {
        primary: fmt.signed(r.amount),
        secondary: r.tax > 0 ? `after ${fmt.money(r.tax)} tax` : 'no tax withheld',
        tone: 'pos' as const
      };
    }
    if (!p) return { primary: '—', secondary: 'no price feed', tone: 'plain' as const };
    if (r.operation === 'Sell') {
      const cost = p.soldCost ?? r.amount;
      const gain = r.amount - cost;
      return {
        primary: fmt.caret(cost ? (gain / cost) * 100 : 0),
        secondary: fmt.signed(gain),
        tone: fmt.tone(gain)
      };
    }
    const gain = r.shares * p.price - r.amount;
    return {
      primary: fmt.caret(r.amount ? (gain / r.amount) * 100 : 0),
      secondary: fmt.signed(gain),
      tone: fmt.tone(gain)
    };
  }

  const sorted = $derived.by(() => {
    const acc: Record<SortKey, (r: LedgerRow) => number> = {
      date: (r) => dateSerial(r.date),
      shares: (r) => r.shares,
      price: (r) => r.price,
      summ: (r) => r.signed,
      profit: (r) => {
        const p = S.prices[r.ticker];
        if (r.kind === 'income') return r.amount;
        if (!p) return 0;
        return r.operation === 'Sell' ? r.amount - (p.soldCost ?? r.amount) : r.shares * p.price - r.amount;
      }
    };
    return filtered.slice().sort((a, b) => (acc[sortKey](a) - acc[sortKey](b)) * sortDir);
  });

  const shown = $derived(sorted.slice(0, limit));

  /** Totals follow the filter, so the strip always describes what is on screen. */
  const totals = $derived.by(() => {
    const pick = (f: (x: LedgerRow) => boolean) =>
      filtered.filter(f).reduce((s, x) => s + x.amount, 0);
    return {
      buy: pick((x) => x.operation === 'Buy'),
      sell: pick((x) => x.operation === 'Sell'),
      income: pick((x) => x.kind === 'income'),
      fee: filtered.reduce((s, x) => s + x.fee, 0),
      tax: filtered.reduce((s, x) => s + x.tax, 0)
    };
  });

  const summary = $derived(
    tab === 'Incomes'
      ? [
          { label: 'Income', value: fmt.money(totals.income), color: 'var(--accent-3)' },
          { label: 'Tax withheld', value: fmt.money(totals.tax), color: 'var(--tag-fg)' }
        ]
      : [
          { label: 'Buy', value: fmt.money(totals.buy), color: 'var(--accent)' },
          { label: 'Sell', value: fmt.money(totals.sell), color: 'var(--grey-series)' },
          { label: 'Fee', value: fmt.money(totals.fee), color: 'var(--tag-fg)' },
          ...(tab === 'All' ? [{ label: 'Income', value: fmt.money(totals.income), color: 'var(--accent-3)' }] : [])
        ]
  );

  function setSort(k: SortKey) {
    if (sortKey === k) sortDir = -sortDir;
    else {
      sortKey = k;
      sortDir = -1;
    }
    limit = PAGE;
  }

  const opTone = (op: string) =>
    op === 'Buy'
      ? { bg: 'var(--accent-soft)', fg: 'var(--accent)' }
      : op === 'Sell'
        ? { bg: 'var(--neg-soft)', fg: 'var(--neg)' }
        : op === 'Dividends'
          ? { bg: 'var(--hover)', fg: 'var(--t1)' }
          : { bg: 'var(--tag-bg)', fg: 'var(--tag-fg)' };

  const gridCols = $derived(
    [
      '44px',
      '132px',
      '218px',
      '116px',
      '116px',
      ...(cols.fee ? ['104px'] : []),
      '126px',
      ...(cols.profit ? ['136px'] : []),
      ...(cols.note ? ['minmax(150px,1fr)'] : [])
    ].join(' ')
  );

  const minWidth = $derived(
    `${44 + 132 + 218 + 116 + 116 + (cols.fee ? 104 : 0) + 126 + (cols.profit ? 136 : 0) + (cols.note ? 150 : 0)}px`
  );

  const allOn = $derived(shown.length > 0 && shown.every((r) => selected.includes(r.id)));

  /** A reconciliation row is only interesting when something failed to close. */
  const reconIssues = $derived(
    S.reconciliation.filter(
      (r) => Math.abs(r.sharesDelta) > 1e-5 || Math.abs(r.costDelta) > 0.01 || Math.abs(r.incomeDelta) > 0.01
    )
  );

  const tone = (t: 'pos' | 'neg' | 'plain') =>
    t === 'pos' ? 'var(--accent)' : t === 'neg' ? 'var(--neg)' : 'var(--t1)';
  const subTone = (t: 'pos' | 'neg' | 'plain') =>
    t === 'pos' ? 'var(--accent)' : t === 'neg' ? 'var(--neg)' : 'var(--t2)';

  const searchItems = $derived(
    Object.keys(S.prices)
      .filter((tk) => S.prices[tk].status === 'open')
      .map((tk) => {
        const row = S.rows.find((r) => r.ticker === tk)!;
        return {
          ticker: tk,
          name: row?.name ?? tk,
          mono: row?.mono ?? tk.slice(0, 2),
          sector: '',
          value: fmt.money(S.prices[tk].price),
          href: `/portfolio/holdings#${tk}`
        };
      })
  );

  const headers = $derived([
    { key: null, label: 'Holding', justify: 'flex-start' },
    { key: 'date' as const, label: 'Date', justify: 'flex-start' },
    { key: 'shares' as const, label: 'Shares', justify: 'flex-end' },
    { key: 'price' as const, label: 'Price', justify: 'flex-end' },
    ...(cols.fee ? [{ key: null, label: 'Fee / Tax', justify: 'flex-end' }] : []),
    { key: 'summ' as const, label: 'Summ', justify: 'flex-end' },
    ...(cols.profit ? [{ key: 'profit' as const, label: 'Total profit', justify: 'flex-end' }] : []),
    ...(cols.note ? [{ key: null, label: 'Note', justify: 'flex-start' }] : [])
  ]);
</script>

<svelte:head><title>Transactions · Snowline</title></svelte:head>
<svelte:window onclick={() => (menu = null)} />

<TopNav
  active="Portfolio"
  subActive="Transactions"
  portfolioName={K.portfolioName}
  holdingsCount={S.totals.holdings}
  {searchItems}
  accountSub={`${K.baseCurrency} · ${S.totals.holdings} holdings`}
/>

<main
  data-r="main"
  style="max-width:1392px;margin:0 auto;padding:24px 24px 88px;display:flex;flex-direction:column;gap:18px"
>
  <div style="display:flex;align-items:flex-start;justify-content:space-between;gap:16px;flex-wrap:wrap">
    <div style="display:flex;flex-direction:column;gap:5px;min-width:0">
      <div style="display:flex;align-items:center;gap:9px">
        <h1 style="margin:0;font-size:32px;font-weight:600;letter-spacing:-0.028em;line-height:1.1;color:var(--t1)">
          Transactions
        </h1>
        <span style="font-size:13px;color:var(--t3);padding-top:6px">{K.portfolioName}</span>
      </div>
      <div style="display:flex;align-items:center;gap:9px;font-size:12px;color:var(--t3)">
        <span>{visible.length} transactions · {S.instrumentCount} instruments</span>
        <span style="width:1px;height:10px;background:var(--line)"></span>
        <span>{fmt.money(S.ledgerTotals.buy)} in buys · {fmt.money(S.totals.invested)} in open positions</span>
      </div>
    </div>
  </div>

  <!-- summary strip -->
  <div
    style="display:grid;grid-template-columns:repeat({summary.length},minmax(0,1fr));gap:0;background:var(--card);border:1px solid var(--line);border-radius:8px;overflow:hidden"
  >
    {#each summary as s (s.label)}
      <div style="display:flex;flex-direction:column;gap:4px;padding:14px 18px;border-right:1px solid var(--line)">
        <span style="display:flex;align-items:center;gap:7px;font-size:11px;color:var(--t3)">
          <span style="width:8px;height:8px;border-radius:2px;background:{s.color}"></span>{s.label}
        </span>
        <span style="font-size:19px;font-weight:600;letter-spacing:-0.02em;color:var(--t1)">{s.value}</span>
      </div>
    {/each}
  </div>

  <!-- toolbar -->
  <div style="display:flex;align-items:center;gap:10px;flex-wrap:wrap">
    <div style="display:flex;align-items:center;gap:2px;border-bottom:1px solid var(--line);flex:none">
      {#each ['Trades', 'Incomes', 'All'] as const as t (t)}
        <button
          onclick={() => { tab = t; limit = PAGE; selected = []; }}
          style="height:34px;padding:0 13px;border:none;border-bottom:2px solid {tab === t ? 'var(--accent)' : 'transparent'};background:transparent;color:{tab === t ? 'var(--t1)' : 'var(--t2)'};font-size:13px;font-weight:{tab === t ? 600 : 500};cursor:pointer;margin-bottom:-1px"
          >{t}</button
        >
      {/each}
    </div>

    <div style="flex:1;min-width:12px"></div>

    <div style="position:relative">
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--t3)" stroke-width="1.8" stroke-linecap="round" style="position:absolute;left:9px;top:8px"><circle cx="11" cy="11" r="7" /><path d="M16.6 16.6L21 21" /></svg>
      <input
        bind:value={query}
        oninput={() => (limit = PAGE)}
        onclick={(e) => e.stopPropagation()}
        placeholder="Search"
        style="height:30px;width:196px;padding:0 10px 0 29px;border:1px solid var(--line);border-radius:6px;background:var(--canvas);color:var(--t1);font-size:12px;outline:none"
      />
    </div>

    <button
      onclick={(e) => { e.stopPropagation(); filtersOpen = !filtersOpen; }}
      style="display:flex;align-items:center;gap:7px;height:30px;padding:0 11px;border:1px solid {ops.length ? 'var(--accent)' : 'var(--line)'};border-radius:6px;background:{ops.length ? 'var(--accent-soft)' : 'var(--card)'};color:{ops.length ? 'var(--accent)' : 'var(--t2)'};font-size:12px;cursor:pointer"
    >
      <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><path d="M4 6h16M7 12h10M10 18h4" /></svg>
      {ops.length ? `Filters · ${ops.length}` : 'Filters'}
    </button>

    <div style="position:relative">
      <button onclick={(e) => { e.stopPropagation(); menu = menu === 'cols' ? null : 'cols'; }} title="Columns" class="icon-btn" style="width:30px;height:30px">
        <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="3" y="4" width="18" height="16" rx="2" /><path d="M9 4v16M15 4v16" /></svg>
      </button>
      {#if menu === 'cols'}
        <div role="menu" tabindex="-1" onclick={(e) => e.stopPropagation()} onkeydown={() => {}}
          style="position:absolute;top:36px;right:0;z-index:40;width:210px;background:var(--card);border:1px solid var(--line);border-radius:8px;box-shadow:var(--shadow);padding:6px">
          {#each [{ k: 'fee' as const, label: 'Fee / Tax' }, { k: 'profit' as const, label: 'Total profit' }, { k: 'note' as const, label: 'Note' }] as c (c.k)}
            <button onclick={() => (cols = { ...cols, [c.k]: !cols[c.k] })}
              style="display:flex;align-items:center;gap:9px;width:100%;height:36px;padding:0 10px;border:none;border-radius:6px;background:transparent;color:var(--t1);font-size:13px;cursor:pointer;text-align:left">
              <span style="width:15px;height:15px;flex:none;border:1px solid {cols[c.k] ? 'var(--accent)' : 'var(--line)'};border-radius:4px;background:{cols[c.k] ? 'var(--accent)' : 'transparent'};color:var(--on-accent);display:flex;align-items:center;justify-content:center;font-size:10px">{cols[c.k] ? '✓' : ''}</span>
              {c.label}
            </button>
          {/each}
        </div>
      {/if}
    </div>
  </div>

  {#if filtersOpen}
    <div style="display:flex;align-items:center;gap:9px;flex-wrap:wrap;padding:11px 14px;border:1px solid var(--line);border-radius:8px;background:var(--card)">
      <span style="font-size:12px;color:var(--t3)">Operation</span>
      {#each ['Buy', 'Sell', 'Dividends', 'Fee'] as o (o)}
        {@const on = ops.includes(o)}
        <button
          onclick={() => { ops = on ? ops.filter((x) => x !== o) : [...ops, o]; limit = PAGE; }}
          style="height:26px;padding:0 11px;border:1px solid {on ? 'var(--accent)' : 'var(--line)'};border-radius:999px;background:{on ? 'var(--accent-soft)' : 'var(--card)'};color:{on ? 'var(--accent)' : 'var(--t2)'};font-size:12px;cursor:pointer"
          >{o}</button
        >
      {/each}
      <div style="flex:1"></div>
      <button onclick={() => { ops = []; query = ''; }} style="border:none;background:transparent;color:var(--t2);font-size:12px;cursor:pointer;padding:0">Reset</button>
    </div>
  {/if}

  {#if selected.length}
    <div style="display:flex;align-items:center;gap:14px;padding:9px 14px;background:var(--accent-soft);border:1px solid var(--line);border-radius:8px">
      <span style="font-size:12px;font-weight:500;color:var(--t1)">{selected.length} selected</span>
      <div style="flex:1"></div>
      <button onclick={() => { deleted = [...deleted, ...selected]; selected = []; }}
        style="border:none;background:transparent;color:var(--neg);font-size:12px;font-weight:500;cursor:pointer;padding:0">Remove from view</button>
      <button onclick={() => (selected = [])} style="border:none;background:transparent;color:var(--t2);font-size:12px;cursor:pointer;padding:0">Clear</button>
    </div>
  {/if}

  <!-- table -->
  <div style="position:relative;max-width:100%;border:1px solid var(--line);border-radius:8px;background:var(--card);overflow-x:auto">
    <div style="min-width:{minWidth}">
      <div style="display:grid;grid-template-columns:{gridCols};border-bottom:1px solid var(--line)">
        <div style="display:flex;align-items:center;justify-content:center;padding:10px 0 10px 12px">
          <span role="checkbox" aria-checked={allOn} tabindex="0" onkeydown={() => {}}
            onclick={(e) => { e.stopPropagation(); selected = allOn ? [] : shown.map((r) => r.id); }}
            style="width:15px;height:15px;border:1px solid {allOn ? 'var(--accent)' : 'var(--line)'};border-radius:4px;background:{allOn ? 'var(--accent)' : 'transparent'};color:var(--on-accent);display:flex;align-items:center;justify-content:center;font-size:10px;cursor:pointer">{allOn ? '✓' : ''}</span>
        </div>
        {#each headers as h, i (h.label + i)}
          <div style="display:flex;align-items:center;justify-content:{h.justify};padding:10px 12px">
            {#if h.key}
              <button onclick={() => setSort(h.key)}
                style="display:flex;align-items:center;gap:5px;border:none;background:transparent;padding:0;cursor:pointer;font-size:12px;font-weight:500;color:{sortKey === h.key ? 'var(--t1)' : 'var(--t2)'}">
                {h.label}<span style="color:var(--accent);font-size:9px;opacity:{sortKey === h.key ? 1 : 0}">{sortDir < 0 ? '▼' : '▲'}</span>
              </button>
            {:else}
              <span style="font-size:12px;font-weight:500;color:var(--t2)">{h.label}</span>
            {/if}
          </div>
        {/each}
      </div>

      {#each shown as r (r.id)}
        {@const isSel = selected.includes(r.id)}
        {@const t = opTone(r.operation)}
        {@const pf = profitOf(r)}
        <div style="display:grid;grid-template-columns:{gridCols};border-bottom:1px solid var(--line);background:{isSel ? 'var(--accent-soft)' : 'var(--card)'}">
          <div style="display:flex;align-items:center;justify-content:center;padding:0 0 0 12px">
            <span role="checkbox" aria-checked={isSel} tabindex="0" onkeydown={() => {}}
              onclick={() => (selected = isSel ? selected.filter((x) => x !== r.id) : [...selected, r.id])}
              style="width:15px;height:15px;border:1px solid {isSel ? 'var(--accent)' : 'var(--line)'};border-radius:4px;background:{isSel ? 'var(--accent)' : 'transparent'};color:var(--on-accent);display:flex;align-items:center;justify-content:center;font-size:10px;cursor:pointer">{isSel ? '✓' : ''}</span>
          </div>

          <div style="display:flex;align-items:center;padding:11px 12px">
            <span style="font-size:11px;font-weight:500;padding:3px 9px;border-radius:999px;background:{t.bg};color:{t.fg};white-space:nowrap">{r.operation}</span>
          </div>

          <div style="display:flex;align-items:center;gap:10px;padding:10px 12px;min-width:0">
            <span class="mono-badge" style="width:28px;height:28px">{r.mono}</span>
            <span style="display:flex;flex-direction:column;gap:1px;min-width:0">
              <a href="/portfolio/holdings#{r.ticker}" style="font-size:13px;font-weight:500;color:var(--t1);text-decoration:none;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">{r.name}</a>
              <span style="font-size:11px;color:var(--t3)">{r.ticker} · {r.date}</span>
            </span>
          </div>

          <div style="display:flex;flex-direction:column;justify-content:center;align-items:flex-end;padding:11px 12px">
            <span style="font-size:13px;color:var(--t1);white-space:nowrap">{fmt.shares(r.shares)}</span>
            <span style="font-size:11px;color:var(--t3)">shares</span>
          </div>

          <div style="display:flex;flex-direction:column;justify-content:center;align-items:flex-end;padding:11px 12px">
            <span style="font-size:13px;color:var(--t1);white-space:nowrap">{fmt.money(r.price)}</span>
            <span style="font-size:11px;color:var(--t3)">per share</span>
          </div>

          {#if cols.fee}
            <div style="display:flex;flex-direction:column;justify-content:center;align-items:flex-end;padding:11px 12px">
              <span style="font-size:13px;color:var(--t1);white-space:nowrap">{r.fee ? fmt.money(r.fee) : '—'}</span>
              <span style="font-size:11px;color:var(--t3)">{r.tax ? `${fmt.money(r.tax)} tax` : 'no tax'}</span>
            </div>
          {/if}

          <div style="display:flex;flex-direction:column;justify-content:center;align-items:flex-end;padding:11px 12px">
            <span style="font-size:13px;font-weight:500;color:{r.signed >= 0 ? 'var(--accent)' : 'var(--t1)'};white-space:nowrap">{fmt.signed(r.signed)}</span>
            <span style="font-size:11px;color:var(--t3)">{r.signed >= 0 ? 'in' : 'out'}</span>
          </div>

          {#if cols.profit}
            <div style="display:flex;flex-direction:column;justify-content:center;align-items:flex-end;padding:11px 12px">
              <span style="font-size:13px;font-weight:500;color:{tone(pf.tone)};white-space:nowrap">{pf.primary}</span>
              <span style="font-size:11px;color:{subTone(pf.tone)};white-space:nowrap">{pf.secondary}</span>
            </div>
          {/if}

          {#if cols.note}
            <div style="display:flex;align-items:center;padding:11px 12px;min-width:0">
              <span style="font-size:12px;color:var(--t3);white-space:nowrap;overflow:hidden;text-overflow:ellipsis">{r.note}</span>
            </div>
          {/if}
        </div>
      {/each}
    </div>
  </div>

  <div style="display:flex;align-items:center;justify-content:space-between;gap:14px">
    <span style="font-size:12px;color:var(--t2)">Showing {shown.length} of {filtered.length}</span>
    {#if shown.length < filtered.length}
      <button onclick={() => (limit += PAGE)}
        style="height:30px;padding:0 14px;border:1px solid var(--line);border-radius:6px;background:var(--card);color:var(--t1);font-size:12px;font-weight:500;cursor:pointer">Load more</button>
    {/if}
  </div>

  <!-- reconciliation -->
  <div class="card">
    <button
      onclick={() => (reconOpen = !reconOpen)}
      style="display:flex;align-items:center;justify-content:space-between;gap:12px;width:100%;padding:15px 20px;border:none;background:transparent;cursor:pointer;text-align:left"
    >
      <span style="display:flex;align-items:center;gap:10px">
        <span class="card-title">Reconciliation</span>
        <span class="card-note">generated rows against the stored positions</span>
      </span>
      <span style="display:flex;align-items:center;gap:9px">
        <span style="font-size:12px;font-weight:500;color:{reconIssues.length ? 'var(--neg)' : 'var(--accent)'}">
          {reconIssues.length ? `${reconIssues.length} not closing` : 'All positions reconcile'}
        </span>
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="var(--t3)" stroke-width="2.2" stroke-linecap="round" style="transform:rotate({reconOpen ? 180 : 0}deg)"><path d="M6 9l6 6 6-6" /></svg>
      </span>
    </button>

    {#if reconOpen}
      <div style="border-top:1px solid var(--line);padding:4px 20px 16px">
        <div style="display:grid;grid-template-columns:minmax(0,1fr) 120px 120px 120px 120px;gap:12px;padding:10px 0;border-bottom:1px solid var(--line);font-size:12px;font-weight:500;color:var(--t2)">
          <span>Holding</span>
          <span style="text-align:right">Shares Δ</span>
          <span style="text-align:right">Cost Δ</span>
          <span style="text-align:right">Income Δ</span>
          <span style="text-align:right">Basis cut</span>
        </div>
        {#each S.reconciliation as r (r.ticker)}
          <div style="display:grid;grid-template-columns:minmax(0,1fr) 120px 120px 120px 120px;gap:12px;padding:9px 0;border-bottom:1px solid var(--line);font-size:12px">
            <span style="display:flex;align-items:center;gap:7px;color:var(--t1)">
              {r.ticker}
              {#if r.splitAdjusted}
                <span style="font-size:10px;color:var(--t3);border:1px solid var(--line);border-radius:3px;padding:0 4px">split-adjusted</span>
              {/if}
            </span>
            <span style="text-align:right;color:{Math.abs(r.sharesDelta) > 1e-5 ? 'var(--neg)' : 'var(--t3)'}">{r.sharesDelta.toFixed(5)}</span>
            <span style="text-align:right;color:{Math.abs(r.costDelta) > 0.01 ? 'var(--neg)' : 'var(--t3)'}">{fmt.money(r.costDelta)}</span>
            <span style="text-align:right;color:{Math.abs(r.incomeDelta) > 0.01 ? 'var(--neg)' : 'var(--t3)'}">{fmt.money(r.incomeDelta)}</span>
            <span style="text-align:right;color:var(--t3)">{r.basisAdjust ? fmt.money(r.basisAdjust) : '—'}</span>
          </div>
        {/each}
        <p style="margin:12px 0 0;font-size:11px;color:var(--t3);line-height:1.55">
          Buy shares are re-adjusted through each ticker's split chain and any return of capital is
          subtracted from the original purchase cost, so a corporate action cannot silently break
          the proof. Income rows reconcile per holding and in total; an individual month will not
          match the received-dividend series, which the value charts are built from.
        </p>
      </div>
    {/if}
  </div>

  <p style="margin:0;font-size:11px;color:var(--t3)">
    Adding, editing and importing transactions are not built in this POC — the prototype's modal
    only mutates its own local state and never recalculates portfolio totals.
  </p>
</main>
