/**
 * Parity against the design prototype.
 *
 * reference.json is generated by running the bundle's own snowline-data.js
 * (see scripts/extract-reference.ts). The TypeScript port must reproduce it
 * to the cent — the prototype is the acceptance criteria, so any drift here
 * is a bug in the port, not a difference of opinion.
 */

import { describe, expect, it } from 'bun:test';
import { editCategories, Engine, type CategoryEdit, type CategoryModel } from '../src/index.js';
import seed from '../../../apps/api/src/db/seed-data.json' with { type: 'json' };
import reference from './reference.json' with { type: 'json' };

const engine = new Engine({
  positions: seed.positions as any,
  constants: seed.constants as any,
  dividendHistory: seed.dividendHistory as any,
  categoryTargets: seed.categoryTargets as any,
  corporateActions: seed.corporateActions as any,
  categoryModel: null
});

/** Money and percentages must agree to well below a displayed digit. */
const near = (a: number, b: number, eps = 1e-9) => expect(Math.abs(a - b)).toBeLessThan(eps);

describe('category editor mutations', () => {
  for (const scenario of reference.categoryEdits) {
    it(scenario.name, () => {
      let categoryModel: CategoryModel | null = null;
      for (const step of scenario.steps) {
        const current = new Engine({
          positions: engine.positions, constants: engine.constants,
          dividendHistory: engine.dividendHistory, categoryTargets: engine.categoryTargets,
          categoryModel
        });
        categoryModel = editCategories(current, step.edit as CategoryEdit);
        expect(categoryModel).toEqual(step.model);
      }
    });
  }
});

describe('totals', () => {
  const T = engine.totals();
  const R = reference.totals;

  it('matches every derived total', () => {
    for (const key of Object.keys(R) as Array<keyof typeof R>) {
      const actual = T[key as keyof typeof T];
      if (typeof actual === 'number' && typeof R[key] === 'number') near(actual, R[key] as number);
      else expect(actual).toEqual(R[key]);
    }
  });

  it('reconciles with the figures stated in the bundle header', () => {
    expect(T.value.toFixed(2)).toBe('30374.48');
    expect(T.invested.toFixed(2)).toBe('28431.28');
    expect(T.capitalGain.toFixed(2)).toBe('1943.20');
    expect(T.totalProfit.toFixed(2)).toBe('3989.53');
    expect(T.dividendsLifetime.toFixed(2)).toBe('1467.21');
    expect(T.realizedPnL.toFixed(2)).toBe('579.12');
    expect(T.forwardGross.toFixed(2)).toBe('1590.07');
    expect(T.grossYield.toFixed(2)).toBe('5.23');
    expect(T.forwardNet.toFixed(2)).toBe('1351.56');
    expect(T.netYield.toFixed(2)).toBe('4.45');
    expect(T.holdings).toBe(12);
  });

  it('keeps the income column summing to its own total', () => {
    const perPosition = engine.open().reduce((s, p) => s + engine.annualGross(p), 0);
    near(perPosition, engine.totals().forwardGross);
  });
});

describe('categories', () => {
  it('matches the reference bucket by bucket', () => {
    const cats = engine.categories();
    expect(cats).toHaveLength(reference.categories.length);
    cats.forEach((c, i) => {
      const r = reference.categories[i];
      expect(c.name).toBe(r.name);
      expect(c.count).toBe(r.count);
      near(c.value, r.value);
      near(c.invested, r.invested);
      near(c.gainAbs, r.gainAbs);
      near(c.gainPctN, r.gainPctN);
      near(c.allocN, r.allocN);
      near(c.targetN, r.targetN);
      near(c.driftN, r.driftN);
    });
  });

  it('allocates exactly 100% across buckets', () => {
    near(engine.categories().reduce((s, c) => s + c.allocN, 0), 100, 1e-9);
  });

  it('seeds a target plan that sums to 100', () => {
    expect(engine.targetTotal()).toBe(100);
  });
});

describe('movers', () => {
  const M = engine.movers();

  it('matches the reference split and sums', () => {
    expect(M.gainers.map((p) => p.ticker)).toEqual(reference.movers.gainers);
    expect(M.losers.map((p) => p.ticker)).toEqual(reference.movers.losers);
    near(M.gainSum, reference.movers.gainSum);
    near(M.lossSum, reference.movers.lossSum);
  });

  it('accounts for the whole day change', () => {
    near(M.gainSum + M.lossSum, engine.totals().dayChange, 1e-9);
  });
});

describe('dividends', () => {
  it('reproduces the received timeline', () => {
    expect(engine.dividendTimeline()).toEqual(reference.dividendTimeline);
  });

  it('reproduces the forward 12 months', () => {
    const fp = engine.forwardPayments();
    expect(fp).toHaveLength(12);
    fp.forEach((m, i) => {
      const r = reference.forwardPayments[i];
      expect(m.full).toBe(r.full);
      near(m.total, r.total);
      near(m.received, r.received);
      expect(m.rows).toHaveLength(r.rows);
    });
  });

  it('matches the forward payment count', () => {
    expect(engine.paymentCountNext12()).toBe(reference.paymentCountNext12);
  });

  it('starts the window at the current month', () => {
    expect(engine.forwardPayments()[0].full).toBe('Aug 2026');
  });
});

describe('goal projection', () => {
  const pr = engine.projection(null);
  const R = reference.projection;

  it('matches the reference path month for month', () => {
    near(pr.current, R.current);
    near(pr.target, R.target);
    near(pr.progressPct, R.progressPct);
    expect(pr.achievable).toBe(R.achievable);
    expect(pr.yearsToGoal).toBe(R.yearsToGoal);
    expect(pr.crossPYear).toBe(R.crossPYear);
    expect(pr.crossSYear).toBe(R.crossSYear);
    expect(pr.span).toBe(R.span);
    expect(pr.startYear).toBe(R.startYear);
    near(pr.endValue, R.endValue, 1e-6);
    near(pr.endSafe, R.endSafe, 1e-6);
    near(pr.shortfall, R.shortfall, 1e-6);
  });

  it('reproduces both series', () => {
    expect(pr.P).toHaveLength(R.P.length);
    pr.P.forEach((v, i) => near(v, R.P[i], 1e-6));
    pr.S.forEach((v, i) => near(v, R.S[i], 1e-6));
  });

  it('starts from today’s portfolio, not a stored number', () => {
    near(pr.startValue, engine.totals().value);
    near(pr.startIncome, engine.totals().forwardGross);
  });

  it('honours a patched config', () => {
    const income = engine.projection({ mode: 'income', incomeTarget: 36000 });
    expect(income.mode).toBe('income');
    expect(income.target).toBe(36000);
    near(income.current, engine.totals().forwardGross);
  });
});

describe('holdings', () => {
  it('gives every open holding a category and a portfolio share', () => {
    const hs = engine.holdings();
    expect(hs).toHaveLength(12);
    hs.forEach((h) => {
      expect(h.categoryName).toBeTruthy();
      expect(h.shareOfPortfolio).toBeGreaterThan(0);
    });
    near(hs.reduce((s, h) => s + h.shareOfPortfolio, 0), 100, 1e-9);
  });

  it('includes sold positions only when asked', () => {
    expect(engine.holdings(true)).toHaveLength(14);
  });

  it('handles a sold position with no cost basis without dividing by zero', () => {
    const tsm = engine.holdings(true).find((h) => h.p.ticker === 'TSM')!;
    expect(tsm.capitalGainPct).toBe(0);
    expect(tsm.yieldOnCost).toBe(0);
    expect(Number.isFinite(tsm.totalProfitPct)).toBe(true);
  });

  it('matches the reference figure for figure', () => {
    const actual = engine.holdings(true);
    reference.holdings.forEach((r) => {
      const h = actual.find((x) => x.p.ticker === r.ticker)!;
      expect(h).toBeDefined();
      near(h.capitalGain, r.capitalGain);
      near(h.capitalGainPct, r.capitalGainPct);
      near(h.totalProfit, r.totalProfit);
      near(h.totalProfitPct, r.totalProfitPct);
      near(h.annualGross, r.annualGross);
      near(h.annualNet, r.annualNet);
      near(h.perShareGross, r.perShareGross);
      near(h.dividendsPerShare, r.dividendsPerShare);
      near(h.yieldOnCost, r.yieldOnCost);
      near(h.shareOfPortfolio, r.shareOfPortfolio);
      near(h.shareOfCategory, r.shareOfCategory);
      expect(h.categoryName).toBe(r.categoryName);
    });
  });
});

describe('ledger', () => {
  const L = engine.ledger;

  it('reproduces every generated row', () => {
    const rows = L.ledger();
    expect(rows).toHaveLength(reference.ledger.length);
    rows.forEach((r, i) => {
      const ref = reference.ledger[i];
      expect(r.id).toBe(ref.id);
      expect(r.kind).toBe(ref.kind);
      expect(r.operation).toBe(ref.operation);
      expect(r.ticker).toBe(ref.ticker);
      expect(r.date).toBe(ref.date);
      near(r.shares, ref.shares);
      near(r.price, ref.price);
      near(r.amount, ref.amount);
      near(r.fee, ref.fee);
      near(r.tax, ref.tax);
      near(r.signed, ref.signed);
    });
  });

  it('matches the reference totals', () => {
    const t = L.ledgerTotals();
    near(t.buy, reference.ledgerTotals.buy);
    near(t.sell, reference.ledgerTotals.sell);
    near(t.income, reference.ledgerTotals.income);
    near(t.fee, reference.ledgerTotals.fee);
    near(t.tax, reference.ledgerTotals.tax);
    expect(t.count).toBe(reference.ledgerTotals.count);
  });

  it('reconciles to the stored positions — the invariant the ledger rests on', () => {
    L.ledgerReconciliation().forEach((r) => {
      expect(Math.abs(r.sharesDelta)).toBeLessThanOrEqual(1e-5);
      expect(Math.abs(r.costDelta)).toBeLessThanOrEqual(0.01);
      expect(Math.abs(r.incomeDelta)).toBeLessThanOrEqual(0.01);
    });
  });

  it('sums income rows to the lifetime dividend total', () => {
    const income = L.ledger()
      .filter((r) => r.kind === 'income')
      .reduce((s, r) => s + r.amount, 0);
    near(income, engine.totals().dividendsReceived, 0.01);
  });

  it('reproduces per-ticker trade lots', () => {
    for (const [ticker, ref] of Object.entries(reference.transactionsFor)) {
      const tx = L.transactionsFor(ticker);
      expect(tx).toHaveLength((ref as any[]).length);
      tx.forEach((t, i) => {
        const r = (ref as any[])[i];
        expect(t.date).toBe(r.date);
        expect(t.type).toBe(r.type);
        near(t.shares, r.shares);
        near(t.price, r.price);
        near(t.total, r.total);
      });
    }
  });

  it('reproduces the seeded price series exactly', () => {
    for (const [ticker, ref] of Object.entries(reference.priceSeries)) {
      const series = L.priceSeries(ticker, 60);
      expect(series).toHaveLength((ref as number[]).length);
      series.forEach((v, i) => near(v, (ref as number[])[i], 1e-9));
    }
  });
});

describe('corporate actions', () => {
  it('reproduces the log event for event', () => {
    const log = engine.ledger.corporateActionLog();
    expect(log).toHaveLength(reference.corporateActionLog.length);
    log.forEach((e, i) => {
      const r = reference.corporateActionLog[i] as any;
      expect(e.id).toBe(r.id);
      expect(e.displayTicker).toBe(r.displayTicker);
      expect(e.pending).toBe(r.pending);
      near(e.sharesBefore, r.sharesBefore);
      near(e.sharesAfter, r.sharesAfter);
      near(e.basisBefore, r.basisBefore);
      near(e.basisAfter, r.basisAfter);
      near(e.perShareBefore, r.perShareBefore);
      near(e.perShareAfter, r.perShareAfter);
    });
  });

  it('matches the reference stats', () => {
    const s = engine.ledger.corporateActionStats();
    const r = reference.corporateActionStats as any;
    expect(s.count).toBe(r.count);
    expect(s.completed).toBe(r.completed);
    expect(s.pending).toBe(r.pending);
    expect(s.tickers).toEqual(r.tickers);
    near(s.basisReduced, r.basisReduced);
    near(s.cash, r.cash);
  });

  it('restates a pre-split lot without changing what the trade cost', () => {
    // NVDA split 4:1 in Jun 2025, so a lot bought before it is shown on its
    // pre-split basis: shares / 4, price × 4, cash total untouched.
    const nvda = engine.byTicker('NVDA')!;
    const lots = engine.ledger.lotsFor(nvda);
    const presplit = lots.filter((l) => l.presplit);
    expect(presplit.length).toBeGreaterThan(0);
    presplit.forEach((l) => near(l.shares * l.price, l.total, 0.02));
  });
});

describe('per-holding dividends', () => {
  it('reproduces the recent payment list', () => {
    for (const [ticker, ref] of Object.entries(reference.dividendsFor)) {
      const divs = engine.dividendsFor(ticker, 5);
      expect(divs).toHaveLength((ref as any[]).length);
      divs.forEach((d, i) => {
        const r = (ref as any[])[i];
        expect(d.payDate).toBe(r.payDate);
        near(d.perShare, r.perShare);
        near(d.gross, r.gross);
        near(d.net, r.net);
      });
    }
  });

  it('returns nothing for a non-payer or a closed position', () => {
    expect(engine.dividendsFor('AMZN')).toHaveLength(0);
    expect(engine.dividendsFor('TSM')).toHaveLength(0);
  });
});

describe('dividend calendar', () => {
  it('reproduces the forward year month for month', () => {
    const year = engine.calendarYear(engine.constants.today.year, engine.constants.today.monthIndex);
    expect(year).toHaveLength(12);
    year.forEach((m, i) => {
      const r = reference.calendarYear[i] as any;
      expect(m.label).toBe(r.label);
      expect(m.short).toBe(r.short);
      expect(m.leadingBlanks).toBe(r.leadingBlanks);
      expect(m.count).toBe(r.count);
      near(m.gross, r.gross);
      near(m.netTotal, r.netTotal);
      near(m.paid, r.paid);
      near(m.declared, r.declared);
      near(m.estimated, r.estimated);
    });
  });

  it('reproduces individual months, including a past one and a year boundary', () => {
    const months = [
      [2026, 0], [2026, 1], [2025, 11], [2026, 7], [2027, 1]
    ] as const;
    months.forEach(([y, mi], i) => {
      const m = engine.calendarMonth(y, mi);
      const r = reference.calendarMonths[i] as any;
      expect(m.label).toBe(r.label);
      expect(m.days).toHaveLength(r.days.length);
      expect(m.events).toHaveLength(r.events.length);
      m.events.forEach((e, j) => {
        const re = r.events[j];
        expect(e.ticker).toBe(re.ticker);
        expect(e.status).toBe(re.status);
        expect(e.payDate).toBe(re.payDate);
        expect(e.exDate).toBe(re.exDate);
        near(e.gross, re.gross);
        near(e.net, re.net);
        near(e.perShare, re.perShare);
      });
    });
  });

  it('agrees with the forward schedule on the current month', () => {
    const { today } = engine.constants;
    const cal = engine.calendarMonth(today.year, today.monthIndex);
    const fwd = engine.forwardPayments()[0];
    near(cal.gross, fwd.total, 1e-9);
  });

  it('marks today only in the current month', () => {
    const { today } = engine.constants;
    const now = engine.calendarMonth(today.year, today.monthIndex);
    expect(now.days.filter((d) => d.isToday)).toHaveLength(1);
    const later = engine.calendarMonth(today.year + 1, today.monthIndex);
    expect(later.days.filter((d) => d.isToday)).toHaveLength(0);
  });

  it('lays every event on a day that exists in the month', () => {
    for (let mi = 0; mi < 12; mi++) {
      const m = engine.calendarMonth(2026, mi);
      m.events.forEach((e) => {
        expect(e.day).toBeGreaterThanOrEqual(1);
        expect(e.day).toBeLessThanOrEqual(m.days.length);
        expect(e.exDay).toBeGreaterThanOrEqual(1);
      });
    }
  });
});
