/**
 * Parity against the design prototype.
 *
 * reference.json is generated by running the bundle's own snowline-data.js
 * (see scripts/extract-reference.ts). The TypeScript port must reproduce it
 * to the cent — the prototype is the acceptance criteria, so any drift here
 * is a bug in the port, not a difference of opinion.
 */

import { describe, expect, it } from 'bun:test';
import { Engine } from '../src/index.js';
import seed from '../../../apps/api/src/db/seed-data.json' with { type: 'json' };
import reference from './reference.json' with { type: 'json' };

const engine = new Engine({
  positions: seed.positions as any,
  constants: seed.constants as any,
  dividendHistory: seed.dividendHistory as any,
  categoryTargets: seed.categoryTargets as any,
  categoryModel: null
});

/** Money and percentages must agree to well below a displayed digit. */
const near = (a: number, b: number, eps = 1e-9) => expect(Math.abs(a - b)).toBeLessThan(eps);

describe('totals', () => {
  const T = engine.totals();
  const R = reference.totals;

  it('matches every derived total', () => {
    for (const key of Object.keys(R) as Array<keyof typeof R>) {
      const actual = T[key as keyof typeof T];
      if (typeof actual === 'number' && typeof R[key] === 'number') near(actual, R[key] as number);
      else expect(actual).toEqual(R[key]);
    }
  });

  it('reconciles with the figures stated in the bundle header', () => {
    expect(T.value.toFixed(2)).toBe('30374.48');
    expect(T.invested.toFixed(2)).toBe('28431.28');
    expect(T.capitalGain.toFixed(2)).toBe('1943.20');
    expect(T.totalProfit.toFixed(2)).toBe('3989.53');
    expect(T.dividendsLifetime.toFixed(2)).toBe('1467.21');
    expect(T.realizedPnL.toFixed(2)).toBe('579.12');
    expect(T.forwardGross.toFixed(2)).toBe('1590.07');
    expect(T.grossYield.toFixed(2)).toBe('5.23');
    expect(T.forwardNet.toFixed(2)).toBe('1351.56');
    expect(T.netYield.toFixed(2)).toBe('4.45');
    expect(T.holdings).toBe(12);
  });

  it('keeps the income column summing to its own total', () => {
    const perPosition = engine.open().reduce((s, p) => s + engine.annualGross(p), 0);
    near(perPosition, engine.totals().forwardGross);
  });
});

describe('categories', () => {
  it('matches the reference bucket by bucket', () => {
    const cats = engine.categories();
    expect(cats).toHaveLength(reference.categories.length);
    cats.forEach((c, i) => {
      const r = reference.categories[i];
      expect(c.name).toBe(r.name);
      expect(c.count).toBe(r.count);
      near(c.value, r.value);
      near(c.invested, r.invested);
      near(c.gainAbs, r.gainAbs);
      near(c.gainPctN, r.gainPctN);
      near(c.allocN, r.allocN);
      near(c.targetN, r.targetN);
      near(c.driftN, r.driftN);
    });
  });

  it('allocates exactly 100% across buckets', () => {
    near(engine.categories().reduce((s, c) => s + c.allocN, 0), 100, 1e-9);
  });

  it('seeds a target plan that sums to 100', () => {
    expect(engine.targetTotal()).toBe(100);
  });
});

describe('movers', () => {
  const M = engine.movers();

  it('matches the reference split and sums', () => {
    expect(M.gainers.map((p) => p.ticker)).toEqual(reference.movers.gainers);
    expect(M.losers.map((p) => p.ticker)).toEqual(reference.movers.losers);
    near(M.gainSum, reference.movers.gainSum);
    near(M.lossSum, reference.movers.lossSum);
  });

  it('accounts for the whole day change', () => {
    near(M.gainSum + M.lossSum, engine.totals().dayChange, 1e-9);
  });
});

describe('dividends', () => {
  it('reproduces the received timeline', () => {
    expect(engine.dividendTimeline()).toEqual(reference.dividendTimeline);
  });

  it('reproduces the forward 12 months', () => {
    const fp = engine.forwardPayments();
    expect(fp).toHaveLength(12);
    fp.forEach((m, i) => {
      const r = reference.forwardPayments[i];
      expect(m.full).toBe(r.full);
      near(m.total, r.total);
      near(m.received, r.received);
      expect(m.rows).toHaveLength(r.rows);
    });
  });

  it('matches the forward payment count', () => {
    expect(engine.paymentCountNext12()).toBe(reference.paymentCountNext12);
  });

  it('starts the window at the current month', () => {
    expect(engine.forwardPayments()[0].full).toBe('Aug 2026');
  });
});

describe('goal projection', () => {
  const pr = engine.projection(null);
  const R = reference.projection;

  it('matches the reference path month for month', () => {
    near(pr.current, R.current);
    near(pr.target, R.target);
    near(pr.progressPct, R.progressPct);
    expect(pr.achievable).toBe(R.achievable);
    expect(pr.yearsToGoal).toBe(R.yearsToGoal);
    expect(pr.crossPYear).toBe(R.crossPYear);
    expect(pr.crossSYear).toBe(R.crossSYear);
    expect(pr.span).toBe(R.span);
    expect(pr.startYear).toBe(R.startYear);
    near(pr.endValue, R.endValue, 1e-6);
    near(pr.endSafe, R.endSafe, 1e-6);
    near(pr.shortfall, R.shortfall, 1e-6);
  });

  it('reproduces both series', () => {
    expect(pr.P).toHaveLength(R.P.length);
    pr.P.forEach((v, i) => near(v, R.P[i], 1e-6));
    pr.S.forEach((v, i) => near(v, R.S[i], 1e-6));
  });

  it('starts from today’s portfolio, not a stored number', () => {
    near(pr.startValue, engine.totals().value);
    near(pr.startIncome, engine.totals().forwardGross);
  });

  it('honours a patched config', () => {
    const income = engine.projection({ mode: 'income', incomeTarget: 36000 });
    expect(income.mode).toBe('income');
    expect(income.target).toBe(36000);
    near(income.current, engine.totals().forwardGross);
  });
});

describe('holdings', () => {
  it('gives every open holding a category and a portfolio share', () => {
    const hs = engine.holdings();
    expect(hs).toHaveLength(12);
    hs.forEach((h) => {
      expect(h.categoryName).toBeTruthy();
      expect(h.shareOfPortfolio).toBeGreaterThan(0);
    });
    near(hs.reduce((s, h) => s + h.shareOfPortfolio, 0), 100, 1e-9);
  });

  it('includes sold positions only when asked', () => {
    expect(engine.holdings(true)).toHaveLength(14);
  });

  it('handles a sold position with no cost basis without dividing by zero', () => {
    const tsm = engine.holdings(true).find((h) => h.p.ticker === 'TSM')!;
    expect(tsm.capitalGainPct).toBe(0);
    expect(tsm.yieldOnCost).toBe(0);
    expect(Number.isFinite(tsm.totalProfitPct)).toBe(true);
  });
});
